FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build
WORKDIR /DockerDemo
# copy csproj and restore as distinct layers
COPY *.sln .
COPY Aspdotnetcore/*.csproj ./Aspdotnetcore/
RUN dotnet restore

# copy everything else and build app
COPY Aspdotnetcore/. ./Aspdotnetcore/
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.1 AS runtime
WORKDIR /DockerDemo/Aspdotnetcore
COPY --from=build /DockerDemo/Aspdotnetcore/out ./
ENTRYPOINT ["dotnet", "Aspdotnetcore.dll"]